# Generated by Django 4.1.4 on 2023-01-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('digital', models.BooleanField(default=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('digital', models.BooleanField(default=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
